### ISSUE TITLE
Add a method which updates the phrase list

### ISSUE THREAD

**Issue by colinkiama** [WilliamABradley/CortanaExtensions#1]
You can basically use the example from this: https://docs.microsoft.com/en-us/cortana/voicecommands/dynamically-modify-voice-command-definition-vcd-phrase-lists

Note: Instead of using "VoiceCommandDefinitionManager.InstalledCommandSets", you should use "VoiceCommandDefinitionManager.InstalledCommandDefintions" instead. Microsoft has forgotten to update their this in the example but everything else works exactly the same.

You could also add an addition methods that update multiple phrase lists and all the phrase lists too

**Comment by WilliamABradley** [comment]
@colinkiama I'll take a look in my spare time to update it.
